apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: server5
spec:
  selector:
    matchLabels:
      app: server5
  template:
    metadata:
      labels:
        app: server5
    spec:
      containers:
      - name: server5
        image: aurelia27/server4:v1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi